CREATE TABLE IF NOT EXISTS player_profile (
    `UUID` VARCHAR(36) NOT NULL,
    `NAME` VARCHAR(16) NOT NULL,
    `RANK` VARCHAR(64) NOT NULL DEFAULT 'Member',
    `GRADE` VARCHAR(64) DEFAULT NULL,
    `POWERLEVEL` INT NOT NULL DEFAULT 100,
    `CURRENCY` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `GLOBALRANK` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `PERMISSIONS` VARCHAR(2048) NOT NULL DEFAULT '[]',
    `IP` VARCHAR(64) NOT NULL DEFAULT '',
    `DEBUGGER` TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`UUID`),
    UNIQUE KEY `uq_player_profile_name` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS retention (
    `UUID` VARCHAR(36) NOT NULL,
    `SPENT` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `TIMEPLAYED` DOUBLE NOT NULL DEFAULT 0,
    `REJOINS` INT NOT NULL DEFAULT 0,
    `PURCHASES` INT NOT NULL DEFAULT 0,
    `CREATOR` VARCHAR(64) DEFAULT NULL,
    `RR` DOUBLE NOT NULL DEFAULT 0,
    `LAST_ACTIVE` DATETIME DEFAULT NULL,
    PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS punish (
    `UUID` VARCHAR(36) NOT NULL,
    `USERNAME` VARCHAR(16) DEFAULT NULL,
    `MUTES` INT NOT NULL DEFAULT 0,
    `KICKS` INT NOT NULL DEFAULT 0,
    `BANS` INT NOT NULL DEFAULT 0,
    `WARNS` INT NOT NULL DEFAULT 0,
    `BANNED` TINYINT(1) NOT NULL DEFAULT 0,
    `WARNED` TINYINT(1) NOT NULL DEFAULT 0,
    `MUTED` TINYINT(1) NOT NULL DEFAULT 0,
    `IPBANNED` TINYINT(1) NOT NULL DEFAULT 0,
    `BAN_START` DATETIME DEFAULT NULL,
    `BAN_END` DATETIME DEFAULT NULL,
    `MUTE_START` DATETIME DEFAULT NULL,
    `MUTE_END` DATETIME DEFAULT NULL,
    `WARN_START` DATETIME DEFAULT NULL,
    `WARN_END` DATETIME DEFAULT NULL,
    `WARN_BY` VARCHAR(64) DEFAULT NULL,
    `BAN_REASON` VARCHAR(255) DEFAULT NULL,
    `BAN_BY` VARCHAR(64) DEFAULT NULL,
    `MUTE_REASON` VARCHAR(255) DEFAULT NULL,
    `WARN_REASON` VARCHAR(255) DEFAULT NULL,
    `MUTE_BY` VARCHAR(64) DEFAULT NULL,
    PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS punish_logs (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `START_DATE` DATETIME DEFAULT NULL,
    `END_DATE` DATETIME DEFAULT NULL,
    `PUNISHMENT` VARCHAR(32) NOT NULL,
    `REASON` VARCHAR(255) DEFAULT NULL,
    `SENDER` VARCHAR(64) DEFAULT NULL,
    `PUNISHED` VARCHAR(64) DEFAULT NULL,
    `PUNISHED_UUID` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `idx_punish_logs_player` (`PUNISHED_UUID`, `PUNISHMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ranks (
    `RANK` VARCHAR(64) NOT NULL,
    `POWERLEVEL` INT NOT NULL DEFAULT 100,
    `PERMISSIONS` VARCHAR(2048) NOT NULL DEFAULT '[]',
    PRIMARY KEY (`RANK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ranks (`RANK`, `POWERLEVEL`, `PERMISSIONS`) VALUES
    ('Member', 100, '[]'),
    ('VIP+', 250, '[]'),
    ('God', 1000, '[]')
ON DUPLICATE KEY UPDATE
    `POWERLEVEL` = VALUES(`POWERLEVEL`),
    `PERMISSIONS` = VALUES(`PERMISSIONS`);
