package com.tjxjnoobie.tools.novuscompose.service;

import com.intellij.openapi.module.Module;
import com.intellij.openapi.module.ModuleManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.roots.ContentEntry;
import com.intellij.openapi.roots.ModuleRootManager;
import com.intellij.openapi.roots.ModuleRootModificationUtil;
import com.intellij.openapi.vfs.LocalFileSystem;
import com.intellij.openapi.vfs.VirtualFile;
import com.tjxjnoobie.tools.novuscompose.analysis.CompositionConstants;
import com.tjxjnoobie.tools.novuscompose.analysis.CompositionModel.MethodModel;
import com.tjxjnoobie.tools.novuscompose.analysis.CompositionModel.MethodSignature;
import com.tjxjnoobie.tools.novuscompose.analysis.CompositionModel.ProjectCompositionState;
import com.tjxjnoobie.tools.novuscompose.analysis.CompositionModel.SourceInterfaceModel;
import com.tjxjnoobie.tools.novuscompose.analysis.CompositionModel.TargetComposition;
import org.jetbrains.jps.model.java.JavaSourceRootType;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

final class ComposedInterfaceGenerator {
    private ComposedInterfaceGenerator() {
    }

    static void write(Project project, ProjectCompositionState state) throws IOException {
        Map<String, Set<Path>> expectedFilesByModule = new HashMap<>();
        for (TargetComposition target : state.targets().values()) {
            Path root = generatedRoot(project, target.moduleName());
            Path file = filePath(root, target.packageName(), target.generatedSimpleName());
            expectedFilesByModule.computeIfAbsent(target.moduleName(), ignored -> new HashSet<>()).add(file);
            Files.createDirectories(file.getParent());
            Files.writeString(file, render(target), StandardCharsets.UTF_8);
            markGeneratedSourceRoot(project, target.moduleName(), root);
        }

        for (Module module : ModuleManager.getInstance(project).getModules()) {
            cleanupStaleFiles(generatedRoot(project, module.getName()), expectedFilesByModule.getOrDefault(module.getName(), Set.of()));
        }
    }

    private static String render(TargetComposition target) {
        StringBuilder builder = new StringBuilder();
        if (!target.packageName().isBlank()) {
            builder.append("package ").append(target.packageName()).append(";\n\n");
        }

        builder.append("// Generated by the Novus Compose IntelliJ plugin. Do not edit.\n");
        builder.append("public interface ").append(target.generatedSimpleName()).append(" {\n");

        for (SourceInterfaceModel source : target.sources()) {
            builder.append("    default ").append(source.qualifiedName()).append(" ")
                    .append(source.resolverName()).append("() {\n");
            builder.append("        return com.tjxjnoobie.api.dependency.DependencyLoaderAccess.findInstance(")
                    .append(source.qualifiedName()).append(".class);\n");
            builder.append("    }\n\n");
        }

        for (Map.Entry<String, List<MethodModel>> entry : target.methodsByName().entrySet()) {
            if (entry.getValue().size() <= 1) {
                continue;
            }
            builder.append("    // Multiple generated methods share the name '").append(entry.getKey()).append("': ");
            builder.append(entry.getValue().stream()
                    .map(method -> method.ownerQualifiedName() + "#" + signatureFor(method).displayName())
                    .reduce((left, right) -> left + "; " + right)
                    .orElse(""));
            builder.append("\n");
        }
        if (!target.methodsByName().isEmpty()) {
            builder.append("\n");
        }

        for (Map.Entry<MethodSignature, List<MethodModel>> entry : target.methodsBySignature().entrySet()) {
            if (entry.getValue().size() != 1) {
                continue;
            }
            MethodModel method = entry.getValue().get(0);
            builder.append("    default ").append(method.returnType()).append(" ")
                    .append(method.generatedMethodName()).append("(").append(parameterDeclaration(method)).append(")")
                    .append(throwsClause(method)).append(" {\n");
            String invocation = method.resolverName() + "()." + method.declaredMethodName() + "(" + argumentList(method) + ")";
            if ("void".equals(method.returnType())) {
                builder.append("        ").append(invocation).append(";\n");
            } else {
                builder.append("        return ").append(invocation).append(";\n");
            }
            builder.append("    }\n\n");
        }

        builder.append("}\n");
        return builder.toString();
    }

    private static String parameterDeclaration(MethodModel method) {
        List<String> parameters = new ArrayList<>();
        for (int i = 0; i < method.parameterTypes().size(); i++) {
            parameters.add(method.parameterTypes().get(i) + " arg" + i);
        }
        return String.join(", ", parameters);
    }

    private static String argumentList(MethodModel method) {
        List<String> arguments = new ArrayList<>();
        for (int i = 0; i < method.parameterTypes().size(); i++) {
            arguments.add("arg" + i);
        }
        return String.join(", ", arguments);
    }

    private static String throwsClause(MethodModel method) {
        return method.thrownTypes().isEmpty() ? "" : " throws " + String.join(", ", method.thrownTypes());
    }

    private static MethodSignature signatureFor(MethodModel method) {
        return new MethodSignature(method.generatedMethodName(), method.parameterTypes(), method.returnType());
    }

    private static Path generatedRoot(Project project, String moduleName) {
        Module module = findModule(project, moduleName);
        if (module != null) {
            VirtualFile[] contentRoots = ModuleRootManager.getInstance(module).getContentRoots();
            if (contentRoots.length > 0) {
                return Path.of(contentRoots[0].getPath(), CompositionConstants.GENERATED_ROOT_DIR, moduleName, "src", "main", "java");
            }
        }
        return Path.of(project.getBasePath(), CompositionConstants.GENERATED_ROOT_DIR, moduleName, "src", "main", "java");
    }

    private static Path filePath(Path root, String packageName, String simpleName) {
        Path packagePath = packageName.isBlank() ? root : root.resolve(packageName.replace('.', java.io.File.separatorChar));
        return packagePath.resolve(simpleName + ".java");
    }

    private static void markGeneratedSourceRoot(Project project, String moduleName, Path root) {
        Module module = findModule(project, moduleName);
        if (module == null) {
            return;
        }
        String rootPath = root.toString();
        for (VirtualFile sourceRoot : ModuleRootManager.getInstance(module).getSourceRoots(JavaSourceRootType.SOURCE)) {
            if (rootPath.equals(sourceRoot.getPath())) {
                return;
            }
        }
        VirtualFile rootFile = LocalFileSystem.getInstance().refreshAndFindFileByPath(rootPath.replace('\\', '/'));
        if (rootFile != null) {
            ModuleRootModificationUtil.updateModel(module, model -> {
                ContentEntry matchingEntry = null;
                for (ContentEntry contentEntry : model.getContentEntries()) {
                    if (rootPath.startsWith(contentEntry.getFile().getPath())) {
                        matchingEntry = contentEntry;
                        break;
                    }
                }
                if (matchingEntry == null && model.getContentEntries().length > 0) {
                    matchingEntry = model.getContentEntries()[0];
                }
                if (matchingEntry == null) {
                    return;
                }
                for (var sourceFolder : matchingEntry.getSourceFolders(JavaSourceRootType.SOURCE)) {
                    if (rootPath.equals(sourceFolder.getFile().getPath())) {
                        return;
                    }
                }
                matchingEntry.addSourceFolder(rootFile, JavaSourceRootType.SOURCE);
            });
        }
    }

    private static Module findModule(Project project, String moduleName) {
        for (Module module : ModuleManager.getInstance(project).getModules()) {
            if (moduleName.equals(module.getName())) {
                return module;
            }
        }
        return null;
    }

    private static void cleanupStaleFiles(Path root, Set<Path> expectedFiles) throws IOException {
        if (!Files.exists(root)) {
            return;
        }
        try (var stream = Files.walk(root)) {
            for (Path path : stream.filter(file -> file.toString().endsWith(".java")).toList()) {
                if (!expectedFiles.contains(path)) {
                    Files.deleteIfExists(path);
                }
            }
        }
    }
}
