plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version '2.18.1'
}

tasks.withType(Test).configureEach {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.named('prepareTestSandbox') {
    disabledPlugins.add('org.jetbrains.plugins.vue')
}

group = 'com.tjxjnoobie'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdea '2025.3'
        bundledPlugin 'com.intellij.java'
        testFramework org.jetbrains.intellij.platform.gradle.TestFrameworkType.Platform.INSTANCE
    }
    implementation 'org.jgrapht:jgrapht-core:1.5.2'
    testImplementation 'junit:junit:4.13.2'
}

intellijPlatform {
    autoReload = true
    pluginConfiguration {
        ideaVersion {
            sinceBuild = '253'
            untilBuild = '253.*'
        }
    }
}
