package com.tjxjnoobie.api.dependency.composition.domains;

// Generated by the Novus Compose IntelliJ plugin. Do not edit.
public interface IInfrastructureDomainGenerated {
    <T> T requireDependency(Class<T> dependencyType);

    default com.tjxjnoobie.api.interfaces.IRank rankDependency() {
        return requireDependency(com.tjxjnoobie.api.interfaces.IRank.class);
    }

    default com.tjxjnoobie.api.interfaces.IUtils utilsDependency() {
        return requireDependency(com.tjxjnoobie.api.interfaces.IUtils.class);
    }

    default com.tjxjnoobie.api.interfaces.IRedis redisDependency() {
        return requireDependency(com.tjxjnoobie.api.interfaces.IRedis.class);
    }

    // Multiple generated methods share the name 'getGameID': com.tjxjnoobie.api.interfaces.IUtils#getGameID(); com.tjxjnoobie.api.interfaces.IUtils#getGameID()
    // Multiple generated methods share the name 'setGameType': com.tjxjnoobie.api.interfaces.IUtils#setGameType(); com.tjxjnoobie.api.interfaces.IUtils#setGameType(com.tjxjnoobie.api.enums.GameTypeEnum)

    default java.lang.String getRank(java.util.UUID arg0) throws java.sql.SQLException {
        return rankDependency().getRank(arg0);
    }

    default int getPowerLevel(java.util.UUID arg0) throws java.sql.SQLException {
        return rankDependency().getPowerLevel(arg0);
    }

    default java.util.Set<java.lang.String> getPermissions(java.util.UUID arg0) throws java.sql.SQLException {
        return rankDependency().getPermissions(arg0);
    }

    default boolean hasPermission(java.util.UUID arg0, java.lang.String arg1) throws java.sql.SQLException {
        return rankDependency().hasPermission(arg0, arg1);
    }

    default java.lang.String getAllRanks() {
        return rankDependency().getAllRanks();
    }

    default void setRankFromUsername(java.lang.String arg0, java.lang.String arg1) throws java.sql.SQLException {
        rankDependency().setRankFromUsername(arg0, arg1);
    }

    default void setRank(java.util.UUID arg0, java.lang.String arg1) throws java.sql.SQLException {
        rankDependency().setRank(arg0, arg1);
    }

    default void revokeRank(java.util.UUID arg0, java.lang.String arg1) throws java.sql.SQLException {
        rankDependency().revokeRank(arg0, arg1);
    }

    default java.util.List<java.lang.String> getRanks() {
        return rankDependency().getRanks();
    }

    default void addRankCache(java.util.UUID arg0) throws java.sql.SQLException {
        rankDependency().addRankCache(arg0);
    }

    default void removeRankCache(java.util.UUID arg0) {
        rankDependency().removeRankCache(arg0);
    }

    default void refreshRankCache(java.util.UUID arg0) throws java.sql.SQLException {
        rankDependency().refreshRankCache(arg0);
    }

    default java.lang.String getCachedRank(java.util.UUID arg0) {
        return rankDependency().getCachedRank(arg0);
    }

    default int getCachedPowerLevel(java.util.UUID arg0) {
        return rankDependency().getCachedPowerLevel(arg0);
    }

    default java.util.Set<java.lang.String> getCachedPermissions(java.util.UUID arg0) {
        return rankDependency().getCachedPermissions(arg0);
    }

    default boolean hasCachedPermission(java.util.UUID arg0, java.lang.String arg1) {
        return rankDependency().hasCachedPermission(arg0, arg1);
    }

    default boolean hasCachedRank(java.util.UUID arg0) {
        return rankDependency().hasCachedRank(arg0);
    }

    default java.util.HashMap<java.util.UUID,java.lang.String> getRankCache() {
        return rankDependency().getRankCache();
    }

    default java.util.HashMap<java.util.UUID,java.lang.Integer> getPowerLevelCache() {
        return rankDependency().getPowerLevelCache();
    }

    default java.util.HashMap<java.util.UUID,java.util.Set<java.lang.String>> getPermissionsCache() {
        return rankDependency().getPermissionsCache();
    }

    default boolean rankExists(java.lang.String arg0) throws java.sql.SQLException {
        return rankDependency().rankExists(arg0);
    }

    default boolean isStaff(java.util.UUID arg0) {
        return rankDependency().isStaff(arg0);
    }

    default boolean isAdmin(java.util.UUID arg0) {
        return rankDependency().isAdmin(arg0);
    }

    default boolean isDonor(java.util.UUID arg0) {
        return rankDependency().isDonor(arg0);
    }

    default java.lang.String getServerID() {
        return utilsDependency().getServerID();
    }

    default void createServerID() {
        utilsDependency().createServerID();
    }

    default void createGameID() {
        utilsDependency().createGameID();
    }

    default java.lang.String generateRandomID(int arg0) {
        return utilsDependency().generateRandomID(arg0);
    }

    default void setGameType() throws java.sql.SQLException {
        utilsDependency().setGameType();
    }

    default java.lang.String getTime() {
        return utilsDependency().getTime();
    }

    default java.lang.String getDate() {
        return utilsDependency().getDate();
    }

    default java.lang.String getAdvancedTime() {
        return utilsDependency().getAdvancedTime();
    }

    default boolean parseBoolean(java.lang.String arg0) {
        return utilsDependency().parseBoolean(arg0);
    }

    default java.lang.String formatTimestamp(java.sql.Timestamp arg0, java.time.format.DateTimeFormatter arg1) {
        return utilsDependency().formatTimestamp(arg0, arg1);
    }

    default java.lang.String formatTime(long arg0) {
        return utilsDependency().formatTime(arg0);
    }

    default java.util.Map<java.lang.String,java.lang.Object> getConfigValues() {
        return utilsDependency().getConfigValues();
    }

    default void setGameType(com.tjxjnoobie.api.enums.GameTypeEnum arg0) throws java.sql.SQLException {
        utilsDependency().setGameType(arg0);
    }

    default void setConfigValue(java.lang.String arg0, java.lang.Object arg1) {
        utilsDependency().setConfigValue(arg0, arg1);
    }

    default java.lang.String getLocalServerID() {
        return utilsDependency().getLocalServerID();
    }

    default void setServerID(java.lang.String arg0) {
        utilsDependency().setServerID(arg0);
    }

    default java.lang.String getMinecraftStaffInGamePrefix() {
        return utilsDependency().getMinecraftStaffInGamePrefix();
    }

    default void setGameID(java.lang.String arg0) {
        utilsDependency().setGameID(arg0);
    }

    default java.lang.String getLocalServerPrefix() {
        return utilsDependency().getLocalServerPrefix();
    }

    default void connectToRedis() {
        redisDependency().connectToRedis();
    }

    default void disconnectFromRedis() {
        redisDependency().disconnectFromRedis();
    }

    default void publishToRedis(java.lang.String arg0) {
        redisDependency().publishToRedis(arg0);
    }

    default void publishRedisUpdate(java.lang.String arg0) {
        redisDependency().publishRedisUpdate(arg0);
    }

    default void handleRedisMessage(java.lang.String arg0) {
        redisDependency().handleRedisMessage(arg0);
    }

}
