package com.tjxjnoobie.api.dependency.composition.domains;

// Generated by ComposesToInterfaceProcessor. Do not edit.
public interface IInfrastructureDomainGenerated {
    default com.tjxjnoobie.api.interfaces.IRank getRank() {
        return com.tjxjnoobie.api.dependency.DependencyLoaderAccess.findInstance(com.tjxjnoobie.api.interfaces.IRank.class);
    }

    default com.tjxjnoobie.api.interfaces.IRedis getRedis() {
        return com.tjxjnoobie.api.dependency.DependencyLoaderAccess.findInstance(com.tjxjnoobie.api.interfaces.IRedis.class);
    }

    default com.tjxjnoobie.api.interfaces.IUtils getUtils() {
        return com.tjxjnoobie.api.dependency.DependencyLoaderAccess.findInstance(com.tjxjnoobie.api.interfaces.IUtils.class);
    }

    // Multiple generated methods share the name 'setGameType': com.tjxjnoobie.api.interfaces.IUtils#setGameType(); com.tjxjnoobie.api.interfaces.IUtils#setGameType(com.tjxjnoobie.api.enums.GameTypeEnum)

    default void addRankCache(java.util.UUID arg0) throws java.sql.SQLException {
        getRank().addRankCache(arg0);
    }

    default void removeRankCache(java.util.UUID arg0) {
        getRank().removeRankCache(arg0);
    }

    default void refreshRankCache(java.util.UUID arg0) throws java.sql.SQLException {
        getRank().refreshRankCache(arg0);
    }

    default java.lang.String getCachedRank(java.util.UUID arg0) {
        return getRank().getCachedRank(arg0);
    }

    default int getCachedPowerLevel(java.util.UUID arg0) {
        return getRank().getCachedPowerLevel(arg0);
    }

    default java.util.Set<java.lang.String> getCachedPermissions(java.util.UUID arg0) {
        return getRank().getCachedPermissions(arg0);
    }

    default boolean hasCachedPermission(java.util.UUID arg0, java.lang.String arg1) {
        return getRank().hasCachedPermission(arg0, arg1);
    }

    default boolean hasCachedRank(java.util.UUID arg0) {
        return getRank().hasCachedRank(arg0);
    }

    default java.util.HashMap<java.util.UUID,java.lang.String> getRankCache() {
        return getRank().getRankCache();
    }

    default java.util.HashMap<java.util.UUID,java.lang.Integer> getPowerLevelCache() {
        return getRank().getPowerLevelCache();
    }

    default java.util.HashMap<java.util.UUID,java.util.Set<java.lang.String>> getPermissionsCache() {
        return getRank().getPermissionsCache();
    }

    default boolean rankExists(java.lang.String arg0) throws java.sql.SQLException {
        return getRank().rankExists(arg0);
    }

    default boolean isStaff(java.util.UUID arg0) {
        return getRank().isStaff(arg0);
    }

    default boolean isAdmin(java.util.UUID arg0) {
        return getRank().isAdmin(arg0);
    }

    default boolean isDonor(java.util.UUID arg0) {
        return getRank().isDonor(arg0);
    }

    default java.lang.String getRank(java.util.UUID arg0) throws java.sql.SQLException {
        return getRank().getRank(arg0);
    }

    default int getPowerLevel(java.util.UUID arg0) throws java.sql.SQLException {
        return getRank().getPowerLevel(arg0);
    }

    default java.util.Set<java.lang.String> getPermissions(java.util.UUID arg0) throws java.sql.SQLException {
        return getRank().getPermissions(arg0);
    }

    default boolean hasPermission(java.util.UUID arg0, java.lang.String arg1) throws java.sql.SQLException {
        return getRank().hasPermission(arg0, arg1);
    }

    default java.lang.String getAllRanks() {
        return getRank().getAllRanks();
    }

    default void setRankFromUsername(java.lang.String arg0, java.lang.String arg1) throws java.sql.SQLException {
        getRank().setRankFromUsername(arg0, arg1);
    }

    default void setRank(java.util.UUID arg0, java.lang.String arg1) throws java.sql.SQLException {
        getRank().setRank(arg0, arg1);
    }

    default void revokeRank(java.util.UUID arg0, java.lang.String arg1) throws java.sql.SQLException {
        getRank().revokeRank(arg0, arg1);
    }

    default java.util.List<java.lang.String> getRanks() {
        return getRank().getRanks();
    }

    default void connectToRedis() {
        getRedis().connectToRedis();
    }

    default void disconnectFromRedis() {
        getRedis().disconnectFromRedis();
    }

    default void publishToRedis(java.lang.String arg0) {
        getRedis().publishToRedis(arg0);
    }

    default void publishRedisUpdate(java.lang.String arg0) {
        getRedis().publishRedisUpdate(arg0);
    }

    default void handleRedisMessage(java.lang.String arg0) {
        getRedis().handleRedisMessage(arg0);
    }

    default java.lang.String getLocalServerID() {
        return getUtils().getLocalServerID();
    }

    default void setServerID(java.lang.String arg0) {
        getUtils().setServerID(arg0);
    }

    default java.lang.String getMinecraftStaffInGamePrefix() {
        return getUtils().getMinecraftStaffInGamePrefix();
    }

    default void setGameID(java.lang.String arg0) {
        getUtils().setGameID(arg0);
    }

    default java.lang.String getLocalServerPrefix() {
        return getUtils().getLocalServerPrefix();
    }

    default java.lang.String getGameID() {
        return getUtils().getGameID();
    }

    default java.lang.String getServerID() {
        return getUtils().getServerID();
    }

    default void createServerID() {
        getUtils().createServerID();
    }

    default void createGameID() {
        getUtils().createGameID();
    }

    default java.lang.String generateRandomID(int arg0) {
        return getUtils().generateRandomID(arg0);
    }

    default void setGameType() throws java.sql.SQLException {
        getUtils().setGameType();
    }

    default java.lang.String getTime() {
        return getUtils().getTime();
    }

    default java.lang.String getDate() {
        return getUtils().getDate();
    }

    default java.lang.String getAdvancedTime() {
        return getUtils().getAdvancedTime();
    }

    default boolean parseBoolean(java.lang.String arg0) {
        return getUtils().parseBoolean(arg0);
    }

    default java.lang.String formatTimestamp(java.sql.Timestamp arg0, java.time.format.DateTimeFormatter arg1) {
        return getUtils().formatTimestamp(arg0, arg1);
    }

    default java.lang.String formatTime(long arg0) {
        return getUtils().formatTime(arg0);
    }

    default java.util.Map<java.lang.String,java.lang.Object> getConfigValues() {
        return getUtils().getConfigValues();
    }

    default void setGameType(com.tjxjnoobie.api.enums.GameTypeEnum arg0) throws java.sql.SQLException {
        getUtils().setGameType(arg0);
    }

    default void setConfigValue(java.lang.String arg0, java.lang.Object arg1) {
        getUtils().setConfigValue(arg0, arg1);
    }

}
